// Generated by Codalio. Runtime ports come from OpenHands Server.
import { defineConfig, mergeConfig } from 'vite';
import baseConfig from './vite.config';

export default defineConfig(async (env) => {
  const apiPort = process.env.API_PORT;
  if (!apiPort) throw new Error('API_PORT is required for Rhino v4 preview');
  const proxyConfig = { server: {
    proxy: { '/api': {
    target: `http://127.0.0.1:${apiPort}`,
    changeOrigin: true,
    ws: true,
  } } } };
  const resolved = typeof baseConfig === 'function'
    ? await baseConfig(env)
    : await baseConfig;
  return mergeConfig(resolved, proxyConfig);
});
