import React from "react";
import { Badge } from "../components/ui/badge";
import { Button } from "../components/ui/button";
import { Card, CardContent } from "../components/ui/card";

import { ArrowRight, Command, PanelsTopLeft, RefreshCw, Sparkles } from "lucide-react";
import { Link } from "react-router-dom";

export default function Landing() {
  return (
    <div className="w-full min-w-0 bg-background text-foreground overflow-x-hidden">
      <div className="mx-auto flex w-full max-w-6xl flex-col gap-10 px-4 py-8 sm:px-6 lg:px-8 lg:py-12 min-w-0">
          <section className="grid gap-6 lg:grid-cols-[1.4fr_0.6fr]"><div className="rounded-xl border border-border bg-card p-8 shadow-sm sm:p-10"><Badge variant="secondary" className="mb-5 gap-2"><Command className="size-3.5" />Engineering signal command center</Badge><h1 className="max-w-3xl text-4xl font-bold tracking-tight text-foreground sm:text-5xl">Your engineering signal, in one decisive view.</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-muted-foreground">Triage work across GitHub, Jira, Slack, Teams, and email without losing context.</p><div className="mt-8 flex flex-wrap gap-3"><Button asChild size="lg"><Link to="/inbox">Open command center <ArrowRight className="ml-2 size-4" /></Link></Button><Button asChild variant="outline" size="lg"><Link to="/dashboard"><PanelsTopLeft className="mr-2 size-4" />See dashboard</Link></Button></div></div><div className="rounded-xl border border-border bg-muted/50 p-6 font-mono text-xs text-muted-foreground"><p className="mb-5 font-sans text-sm font-semibold text-foreground">Move at keyboard speed</p><div className="space-y-3"><div className="flex justify-between"><span>Command palette</span><kbd className="rounded bg-card px-2 py-1 text-foreground">⌘K</kbd></div><div className="flex justify-between"><span>Navigate queue</span><kbd className="rounded bg-card px-2 py-1 text-foreground">j / k</kbd></div><div className="flex justify-between"><span>Resolve item</span><kbd className="rounded bg-card px-2 py-1 text-foreground">e</kbd></div><div className="flex justify-between"><span>Delegate</span><kbd className="rounded bg-card px-2 py-1 text-foreground">m</kbd></div></div></div></section>
  <section className="space-y-5"><div><Badge variant="outline">Designed for focus</Badge><h2 className="mt-3 text-2xl font-bold tracking-tight text-foreground">Built for high-velocity engineering teams</h2></div><div className="grid gap-4 md:grid-cols-3">{[{ icon: PanelsTopLeft, title: "Multi-pane triage", description: "Master list and source context stay visible." }, { icon: RefreshCw, title: "Bi-directional sync", description: "Updates flow back to every connected tool." }, { icon: Sparkles, title: "Signal prioritization", description: "Blockers and executive requests rise first." }].map(({ icon: Icon, title, description }) => <Card key={title} className="shadow-sm"><CardContent className="p-5"><div className="mb-4 grid size-10 place-items-center rounded-lg bg-accent text-accent-foreground"><Icon className="size-5" /></div><h3 className="font-semibold text-foreground">{title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{description}</p></CardContent></Card>)}</div></section>
  <section className="rounded-xl bg-primary p-6 text-primary-foreground sm:p-8"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-center"><div><h2 className="text-2xl font-bold tracking-tight">Clear the queue before it clears your day.</h2><p className="mt-2 text-sm text-primary-foreground/80">Bring every signal, owner, and source into focus.</p></div><Button asChild size="lg" variant="secondary"><Link to="/inbox">Start triage <ArrowRight className="ml-2 size-4" /></Link></Button></div></section>
      </div>
    </div>
  );
}